micronaut:
  application:
    name: videoMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
        packages:
            - york.eng2.video.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka: 
    enabled:false
netty:
  default:
    allocator:
      max-order: 3
url:
    jdbc:
        mariadb://localhost:3306/videos
username: todo
password: todosecrets